server:
  port: 8100
spring:
  profiles:
    active: default
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  batch:
    job:
      enabled: false
#  session:
#    store-type: redis
#  redis:
# 각자 노트북의 REDIS
#    host: 127.0.0.1
#    port: 6379
#    password: efws
#    database: 0
#    password: efws12!@

# 기홍 개인 REDIS(비밀번호 없음, 회사 외부에서 가능)
#    host: helpot.iptime.org
#    port: 6379
#    password:
     
  datasource:
## 회사 개발 DB의 efws_app 계정
    url: jdbc:mysql://
    username: 아이디
    password: 비번
    driver-class-name: com.mysql.jdbc.Driver

# 각자 노트북의 DB
#    url: jdbc:mysql://localhost:3306/efws?useSSL=false
#    username: EFWS
#    password: elandFood12!@
#    driver-class-name: com.mysql.jdbc.Driver
#              
  jpa:
    hibernate:
      ddl-auto: update
